name: ci

on: [push, pull_request]

jobs:
  oak:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v4

      - name: install deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.X

      - name: check format
        run: deno fmt --check

      - name: check linting
        run: deno lint

      - name: check publish
        run: deno publish --dry-run

      - name: run tests generating coverage
        run: deno task test:coverage

      - name: generate lcov
        run: deno task coverage > cov.lcov

      - name: upload coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./cov.lcov
          token: ${{ secrets.CODECOV_TOKEN }}
